// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
	"log/slog"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.App, slogger *slog.Logger) (*boot.Bootstrap, func(), error) {
	onStartHooks := NewOnStarts(app)
	onStopHooks := NewOnStops(app)
	server := NewHttpServer(app)
	v := NewComponents(server)
	v2 := NewComponentBuilders()
	bootstrap := boot.New(onStartHooks, onStopHooks, v, v2)
	return bootstrap, func() {
	}, nil
}
