version: '3'

vars:
  Version: v0.7.1
  Comment: "release v0.7.1"

tasks:
  release-tag:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - git tag -a {{ .Version }} -m "{{ .Comment }}"
      - git push origin {{ .Version }}

  release-all:
    cmds:
      - task: release-tag
        vars:
          Version: "{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/zap/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/pubsub/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/kafka/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/schedule/{{.Version}}"
          Comment: "{{.Comment}}"
