version: '3'

vars:
  Version: v1.5.0
  Comment: "release v1.5.0"

tasks:
  release-tag:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - git tag -a {{ .Version }} -m "{{ .Comment }}"
      - git push origin {{ .Version }}

  release-all:
    cmds:
      - task: release-tag
        vars:
          Version: "{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/zap/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/watermill/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/watermill-kafka/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/telemetry/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/schedule/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/registry/{{.Version}}"
          Comment: "{{.Comment}}"
      - task: release-tag
        vars:
          Version: "contrib/consul/{{.Version}}"
          Comment: "{{.Comment}}"
