version: '3'

env:
  RELEASE_VERSION: v0.6.6
  RELEASE_COMMENT: "release v0.6.6: handle kafka consume error"

tasks:
  release-tag:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - git tag -a {{ .Version }} -m "{{ .Comment }}"
      - git push origin {{ .Version }}

  release-all:
    cmds:
      - task: release-tag
        vars:
          Version: $RELEASE_VERSION
          Comment: $RELEASE_COMMENT
      - task: release-tag
        vars:
          Version: contrib/zap/$RELEASE_VERSION
          Comment: $RELEASE_COMMENT
      - task: release-tag
        vars:
          Version: contrib/pubsub/$RELEASE_VERSION
          Comment: $RELEASE_COMMENT
      - task: release-tag
        vars:
          Version: contrib/kafka/$RELEASE_VERSION
          Comment: $RELEASE_COMMENT
      - task: release-tag
        vars:
          Version: contrib/schedule/$RELEASE_VERSION
          Comment: $RELEASE_COMMENT
