// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.App) (*boot.Bootstrap, func(), error) {
	onStartHooks := NewOnStarts()
	onStopHooks := NewOnStops()
	memoryTransport := NewMemoryTransport()
	config := NewConfig(app)
	transport, err := NewKafkaTransport(config)
	if err != nil {
		return nil, nil, err
	}
	broker, err := NewBroker(config, transport, memoryTransport)
	if err != nil {
		return nil, nil, err
	}
	v := NewHandlers()
	router := NewRouter(broker, v)
	server := NewHttpServer(broker)
	v2 := NewServices(memoryTransport, transport, broker, router, server)
	v3 := NewServiceFactories()
	bootstrap := boot.New(onStartHooks, onStopHooks, v2, v3)
	return bootstrap, func() {
	}, nil
}
