// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/bootstrap"
	"log/slog"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.Lynx, slogger *slog.Logger) (*bootstrap.Bootstrap, func(), error) {
	onStartHooks := NewOnStarts(app)
	onStopHooks := NewOnStops(app)
	server := NewHttpServer(app)
	v := NewComponents(server)
	v2 := NewComponentFactories()
	bootstrapBootstrap := bootstrap.New(onStartHooks, onStopHooks, v, v2)
	return bootstrapBootstrap, func() {
	}, nil
}
