// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
)

// Injectors from wire.go:

func wireApp(app lynx.App) (*App, func(), error) {
	preStartHooks := NewPreStarts(app)
	drainHooks := NewDrains()
	preStopHooks := NewPreStops()
	postStopHooks := NewPostStops()
	appConfig, err := NewConfig(app)
	if err != nil {
		return nil, nil, err
	}
	store, err := NewStore(appConfig)
	if err != nil {
		return nil, nil, err
	}
	v := NewServices(store)
	v2 := NewServiceFactories()
	bootstrap := boot.New(preStartHooks, drainHooks, preStopHooks, postStopHooks, v, v2)
	deps := NewDeps(store)
	mainApp := NewApp(bootstrap, deps)
	return mainApp, func() {
	}, nil
}
